### ISSUE TITLE
RHEL/CentOS: repo uri list incorrect

### ISSUE THREAD

**Issue by Klaas-** [Azure/updatemanagement#10]
Hi,
1) you have two functions that do the same:
https://github.com/Azure/updatemanagement/blob/2c265cd2d2f70fd090fada2b32222e09c8ca76ef/UM_Linux_Troubleshooter_Offline.py#L919
https://github.com/Azure/updatemanagement/blob/2c265cd2d2f70fd090fada2b32222e09c8ca76ef/UM_Linux_Troubleshooter_Offline.py#L939

As centos and rhel are essentially the same thing, one method that works correctly should suffice

2) currently you search grep for urls in /etc/yum.repos.d, this will give you a lot of false positives for repo urls because you do not differentiate between enabled and disabled repos. I am guessing it would be easiest to just use dnf/yum functions directly or use the yum/dnf subcommands directly, for example repolist could be a good idea.

Greetings
Klaas

**Comment by swjai** [comment]
Fixed.
