### ISSUE TITLE
Link on var points to 404 

### ISSUE THREAD

**Issue by ghost** [Azure/updatemanagement#11]
@swjai, Good evening, on the line below, the link is a 404 
https://github.com/Azure/updatemanagement/blob/2c265cd2d2f70fd090fada2b32222e09c8ca76ef/UM_Linux_Troubleshooter_Offline.py#L1160

Wouldn't it make more sense to point that variable to this link:
https://docs.microsoft.com/en-us/azure/automation/update-management/operating-system-requirements

and include:  re.search("Ubuntu-20.04", os_version, re.IGNORECASE)
In the check_os_version() function?

**Comment by swjai** [comment]
@RafaelRuales correct. Link has changed. Thanks for pointing out. We'll fix it.

**Comment by swjai** [comment]
Handled.
