### ISSUE TITLE
Script UM_Linux_Troubleshooter_Offline.py doesn't set timeout for socket operations

### ISSUE THREAD

**Issue by alisson276** [Azure/updatemanagement#13]
The script doesn't set a simple timeout when doing socket.socket(). In my environment the script got stuck until I realize this.

[after this](https://github.com/Azure/updatemanagement/blob/main/UM_Linux_Troubleshooter_Offline.py#L1391) it needs a 
```
sock.settimeout(30)
```

or something similar.

**Comment by swjai** [comment]
Incorporated.
