### ISSUE TITLE
China East 2 failed but working

### ISSUE THREAD

**Issue by red-erik** [Azure/updatemanagement#15]
Hello,
Thank you for this great tool.
I'm using this script to troubleshoot agent communication. The script always fails on this test:
RuleId                      : AutomationAgentServiceConnectivityCheck1
RuleGroupId                 : connectivity
RuleName                    : Registration endpoint
RuleGroupName               : connectivity
RuleDescription             : Proxy and firewall configuration must allow Automation Hybrid Worker agent to
                              communicate with xxxx.agentsvc.azure-automation.net
CheckResult                 : Failed
CheckResultMessage          : TCP Test for xxxx.agentsvc.azure-automation.net (port
                              443) failed
CheckResultMessageId        : AutomationAgentServiceConnectivityCheck1.Failed
CheckResultMessageArguments : {xxxx.agentsvc.azure-automation.net}

but from the portal the agent is correctly installed and configured.
I suppose that for China the address should not be "agentsvc.azure-automation.net" but a different one.
https://docs.microsoft.com/en-us/azure/automation/how-to/automation-region-dns-records

Regards,

Red.

**Comment by swjai** [comment]
From the code, it looks for agentsvc url in "/etc/opt/microsoft/omsagent/conf/omsadmin.conf"
The agentsvc url fetched seems to be .net in the file 

this looks like a real issue, the one not with trubleshooter.
