### ISSUE TITLE
LookupError: unknown encoding: binary

### ISSUE THREAD

**Issue by jun110** [Azure/updatemanagement#21]
Hi.
When I run the current latest version of UM_Linux_Troubleshooter_Offline.py, I get the following error

```.sh
$ sudo python3 UM_Linux_Troubleshooter_Offline.py
Processing Information...[can take upto 5 minutes]
Traceback (most recent call last):
  File "UM_Linux_Troubleshooter_Offline.py", line 1463, in <module>
    main()
  File "UM_Linux_Troubleshooter_Offline.py", line 1063, in main
    check_hybrid_worker_running()
  File "UM_Linux_Troubleshooter_Offline.py", line 1232, in check_hybrid_worker_running
    resourceSetting = find_line_in_file("ResourceSettings", current_mof, current_mof_encoding);
  File "UM_Linux_Troubleshooter_Offline.py", line 1424, in find_line_in_file
    current_file = codecs.open(path, "r", file_encoding)
  File "/usr/lib/python3.6/codecs.py", line 900, in open
    info = lookup(encoding)
LookupError: unknown encoding: binary
```

Does anyone know of a solution?

## My Environments
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Python 3.6.9

**Comment by sainsb** [comment]
Same here

**Comment by ghost** [comment]
Same error on RedHat

**Comment by DevMan01** [comment]
+ 1

> NAME="Red Hat Enterprise Linux"
> VERSION="8.2 (Ootpa)"
> ID="rhel"
> ID_LIKE="fedora"
> VERSION_ID="8.2"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
> HOME_URL="https://www.redhat.com/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> 
> REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
> REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
> REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
