### ISSUE TITLE
No Python3 compatibility

### ISSUE THREAD

**Issue by ruffy91** [Azure/updatemanagement#3]
Please add compatibility for python3, as python2 is no longer supported.
For example Ubuntu 20.04 has no python2 installed per default, also the compatibility warning in the code does obviously not work, as there are syntax errors for python3 in the code.

**Comment by jonbrefe** [comment]
Can you check again? Apparently the code to support python 3 was added on Feb 24th https://github.com/Azure/updatemanagement/commit/c89cf17961ec9d16ee5a107e78ce7de69ab3b20d

**Comment by swjai** [comment]
Compatible now.
