### ISSUE TITLE
Ping is a bad test for Linux repository health checks

### ISSUE THREAD

**Issue by ph84172** [Azure/updatemanagement#8]
The Linux Offline Troubleshooter script attempts to ping each configured update repository on the system as a basic health check (at least it does on CentOS/Yum, haven't checked other platforms).  This is a bad test as some repositories aren't pingable - one such repository is packages.microsoft.com.

Example:

    Debug: mirrorlist.centos.org Ping successful!
    Debug: packages.microsoft.com Ping unsuccessful.
    Debug: Error - Not able to ping all repositories!
    Debug: Access Check for Repo failed !
    Failed: Some of the repositories configured could not be accessed

**Comment by swjai** [comment]
Fixed.
